# Final Web Scraper for Reddit

## Imports

In [5]:
import praw
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Reddit Authentification

In [6]:
#create request
reddit = praw.Reddit(client_id='4-rymST_4DmH0Q',
                     client_secret="NOvMOy9faobYCfP2r6LQbUcn_wM", password='12345ABCabc!',
                     user_agent='a', username='aps360')

## Scraping Loop

In [22]:
df = pd.DataFrame()
#columns=["id","title","num_comments","score","upvote_ratio","comment_forest","url"]



# List of subreddits we want to get data from
subreddits =['history','AskEurope','AskMen','Showerthoughts','Jokes','legaladvice','LifeProTips',
             'personalfinance','personalfinancecanada','TwoXChromosomes','Relationships','TalesFromRetail',
             'books']
count = 0

# Create list to hold the dictionaries

dict_list = []

# Loop through subreddits

for sr in subreddits:
    
    subreddit = reddit.subreddit(sr)
    
    # Take the top 1000 posts from all time

    for submission in subreddit.top(time_filter='all',limit=1000):
        data = {}
        data['id'] = count
        data['subreddit'] = sr
        data['title'] = submission.title
        data['post'] = (submission.selftext)
        data['score'] = submission.score
        data['url'] = submission.url
        
        # Update count
        
        count = count + 1
        
        # For visibility purposes during runtime

        if count%500==0:
            print(count,sr)
            
        # Append the dictionary to dict_list
        
        dict_list.append(data)

500 history
1000 AskEurope
1500 AskEurope
2000 AskMen
2500 AskMen
3000 Showerthoughts
3500 Showerthoughts
4000 Jokes
4500 Jokes
5000 legaladvice
5500 legaladvice
6000 LifeProTips
6500 LifeProTips
7000 personalfinance
7500 personalfinance
8000 personalfinancecanada
8500 personalfinancecanada
9000 TwoXChromosomes
9500 TwoXChromosomes
10000 Relationships
10500 Relationships
11000 TalesFromRetail
11500 TalesFromRetail
12000 books
12500 books

In [23]:
df = pd.DataFrame(dict_list)
df.head(30)

,id,post,score,subreddit,title,url
0,0,,53782,history,"New ""Discovery Mode"" turns video game ""Assassi...",https://www.theverge.com/2018/2/20/17033024/as...
1,1,"Hi everyone and especially our students,\n\nWe...",38426,history,We are not here to help you with your End of T...,https://www.reddit.com/r/history/comments/8pw3...
2,2,,35982,history,A 1776 excerpt from John Adam's diary where he...,https://founders.archives.gov/documents/Adams/...
3,3,,34908,history,Famous Viking warrior burial revealed to be th...,http://www.news.com.au/technology/science/arch...
4,4,,34197,history,"3,000-year-old underwater castle discovered in...",https://inhabitat.com/3000-year-old-underwater...
5,5,,34065,history,Researchers built a database from 4000 year ol...,https://www.washingtonpost.com/news/wonk/wp/20...
6,6,My grandfather-in-law was a Jewish-American Of...,33453,history,My Jewish-American grandfather guarded Nazis i...,https://www.reddit.com/r/history/comments/6ujl...
7,7,,32168,history,700-year-old Knights Templar cave discovered i...,http://www.bbc.com/news/uk-england-39193347
8,8,,31549,history,"The ""Harlem Hellfighters"" were the first Afric...",https://www.youtube.com/watch?app=desktop&pers...
9,9,,31466,history,"In 1830, American consumption of alcohol, per ...",https://www.pastemagazine.com/articles/2018/08...
10,10,,28147,history,"40,000-year-old bracelet made by extinct human...",http://www.digitaljournal.com/science/40-000-y...
11,11,,27450,history,The Last Slave Ship Survivor Gave an Interview...,http://www.history.com/news/zora-neale-hurston...
12,12,">The counts of the indictment are luxury, bad ...",25855,history,"The more things change, the more they stay the...",https://www.reddit.com/r/history/comments/7btv...
13,13,,25666,history,"Today is the 2700th birthday of Rome, here is ...",https://www.youtube.com/watch?v=R1XOcuTn3x4
14,14,"I find fashion history pretty interesting, and...",25609,history,What women's fashion looked like in every year...,https://www.reddit.com/r/history/comments/6luh...
15,15,,25084,history,An ancient tablet engraved with 13 verses of t...,http://www.france24.com/en/20180710-ancient-ta...
16,16,,25043,history,Archaeologists Find Lost Ancient Greek Temple ...,http://www.ibtimes.com/archaeologists-find-los...
17,17,"According to a report in Ahram Online, an inta...",24800,history,"3,800-year-old Egyption Tomb Found, Intact and...",https://www.reddit.com/r/history/comments/61zo...
18,18,,24772,history,Rare footage of interviews with elderly people...,https://www.youtube.com/watch?v=0FE30a4J38Q
19,19,,24765,history,World's oldest person Emma Morano dies at 117,http://www.bbc.co.uk/news/amp/39610937
20,20,,24736,history,Mass grave in England may belong to Viking Gre...,https://www.cnn.com/2018/02/02/health/viking-g...
21,21,,24222,history,How the United States Looked Before the EPA,http://fortune.com/2017/02/28/how-the-united-s...
22,22,,24127,history,DNA Samples Reveal That Aboriginals Have Been ...,http://sciencenewsjournal.com/dna-samples-reve...
23,23,2 other examples I love are that Dinosaurs had...,23916,history,TIL that Ancient Greek ruins were actually col...,https://www.reddit.com/r/history/comments/6l7r...
24,24,"On May 11 1960, Adolf Eichmann, a Nazi Lieuten...",22382,history,With the surprising number of commenters in va...,https://www.reddit.com/r/history/comments/8gh2...
25,25,,22180,history,Oral testimony of an Aboriginal massacre now s...,https://theconversation.com/oral-testimony-of-...
26,26,,22138,history,112-year-old Francisco Núñez Olivera fought in...,https://www.thelocal.es/20160125/spaniard-is-w...
27,27,,21999,history,Plane crash that killed UN boss 'may have been...,https://www.theguardian.com/world/2017/sep/26/...
28,28,EDIT: Thanks so much for all your questions! S...,21439,history,I’m Dr. Bob Ballard and I’m the oceanographer ...,https://www.reddit.com/r/history/comments/7eim...
29,29,,21059,history,"A century ago, New York City passed the first-...",https://www.youtube.com/watch?v=lGroIrQmwyw

In [11]:
# Write the file to csv

df.to_csv("updated_data.csv")

## Quick Data Cleaning

In [24]:
df.isnull().sum()

id           0
post         0
score        0
subreddit    0
title        0
url          0
dtype: int64

Some posts should be null as not all the posts should have text, I will correct this by replacing the blank spaces with nulls:

In [25]:
for i in range(len(df.post)):
    if i%500==0:
        print(i-1)
    try:
        if df.post[i]=="":
            df.post[i] = np.nan
    except:
        continue

-1

C:\Users\Matthew\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

499
999
1499
1999
2499
2999
3499
3999
4499
4999
5499
5999
6499
6999
7499
7999
8499
8999
9499
9999
10499
10999
11499
11999
12499

Let's see if the above loop worked:

In [26]:
df.isnull().sum()

id              0
post         3439
score           0
subreddit       0
title           0
url             0
dtype: int64

Looks like that worked, let's now map the subreddits into numbers so that we can input the data into a neural network:

In [27]:
# Map categorical variables

sr = df.subreddit.unique()
for i in range(0,len(sr)):
    map = {sr[i]:i}
    df.replace(map,inplace=True)

df.head()

,id,post,score,subreddit,title,url
0,0,NaN,53782,0,"New ""Discovery Mode"" turns video game ""Assassi...",https://www.theverge.com/2018/2/20/17033024/as...
1,1,"Hi everyone and especially our students,\n\nWe...",38426,0,We are not here to help you with your End of T...,https://www.reddit.com/r/history/comments/8pw3...
2,2,NaN,35982,0,A 1776 excerpt from John Adam's diary where he...,https://founders.archives.gov/documents/Adams/...
3,3,NaN,34908,0,Famous Viking warrior burial revealed to be th...,http://www.news.com.au/technology/science/arch...
4,4,NaN,34197,0,"3,000-year-old underwater castle discovered in...",https://inhabitat.com/3000-year-old-underwater...

In [28]:
# Check value_counts

df.subreddit.value_counts()

11    1000
1     1000
8      999
4      998
12     994
0      991
7      983
2      978
5      976
9      976
3      920
10     901
6      883
Name: subreddit, dtype: int64

Everything checks out so let's write this into a final updated csv:

In [29]:
df.to_csv("updated_datav2.csv")